Updated Login Page UI
Program run on window but not Linux

Error: Linux is cap sensitive when it come to #include and a file name.

Fixed: Change all filename to match with #include on the necessary file

Extra: Clean up some code and added comment

Tested on WINDOW: Run as expected

Need to be tested on LINUX